leftnav:
- identifier: b9171f01-a213-5b02-af78-d1367477d5dd
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: da4d9c64-54ac-2506-d73b-5ed1c5d32f0b
  name: Readings
  pageRef: /pages/readings
  weight: 20
- identifier: 5738a32e-91e6-38d9-b04a-a428a6dce0fd
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 30
- identifier: 42f328ed-54db-ed60-3e8c-d692f70d4051
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 72a7acb4-b07d-269a-9713-e952f0f31807
  name: Projects
  pageRef: /pages/projects
  weight: 50
- identifier: 7783f241-3742-cfd2-9ee3-04b1ce8a4e5c
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
